name: simdart_demo
description: "SimDart Demo"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  demoflu: ^2.5.0
  simdart: #^0.1.0-rc.2
    path: ../simdart
  chart_sparkline: ^1.1.1
  davi: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - lib/production_line/
